OENIK_PROG3_2020_2_YR1IG6/WebApp/Models/Lemez.cs
// <copyright file="Lemez.cs" company="PlaceholderCompany">
// Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>

namespace WebApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;
    using System.Threading.Tasks;

    /// <summary>
    /// Lemez class.
    /// </summary>
    public class Lemez
    {
        /// <summary>
        /// Gets or sets LemezID.
        /// </summary>
        [Display(Name = "Lemez ID")]
        [Required]
        public int LemezID { get; set; }

        /// <summary>
        /// Gets or sets Stilus.
        /// </summary>
        [Display(Name = "Stílus")]
        public string Stilus { get; set; }

        /// <summary>
        /// Gets or sets Tipus.
        /// </summary>
        [Display(Name = "Típus")]
        [StringLength(2, MinimumLength = 2)]
        public string Tipus { get; set; }

        /// <summary>
        /// Gets or sets Eloado.
        /// </summary>
        [Display(Name = "Előadó")]
        [Required]
        public string Eloado { get; set; }

        /// <summary>
        /// Gets or sets LemezCim.
        /// </summary>
        [Display(Name = "Lemez cím")]
        [Required]
        public string LemezCim { get; set; }

        /// <summary>
        /// Gets or sets KiadasEve.
        /// </summary>
        [Display(Name = "Kiadás éve")]
        [StringLength(4, MinimumLength = 4)]
        public string KiadasEve { get; set; }
    }
}

OENIK_PROG3_2020_2_YR1IG6/WebApp/Models/LemezListViewModel.cs
// <copyright file="LemezListViewModel.cs" company="PlaceholderCompany">
// Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>

namespace WebApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;

    /// <summary>
    /// LemezListViewModel class.
    /// </summary>
    public class LemezListViewModel
    {
        /// <summary>
        /// Gets or sets ListOfLemez.
        /// </summary>
        public IEnumerable<Lemez> ListOfLemez { get; set; }

        /// <summary>
        /// Gets or sets EditedLemez.
        /// </summary>
        public Lemez EditedLemez { get; set; }
    }
}

OENIK_PROG3_2020_2_YR1IG6/WebApp/Controllers/LemezController.cs
// <copyright file="LemezController.cs" company="PlaceholderCompany">
// Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>

namespace WebApp.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using AutoMapper;
    using LemezBolt.Logic;
    using Microsoft.AspNetCore.Mvc;
    using WebApp.Models;

    /// <summary>
    /// LemezController class.
    /// </summary>
    [CLSCompliant(false)]
    public class LemezController : Controller
    {
        private IBeszerzoLogic beszerzoLogic;
        private ITulajdonosLogic tulajLogic;
        private IMapper mapper;
        private LemezListViewModel vm;

        /// <summary>
        /// Initializes a new instance of the <see cref="LemezController"/> class.
        /// </summary>
        /// <param name="beszerzoLogic">IBeszerzoLogic instance.</param>
        /// <param name="tulajLogic">ITulajdonosLogic instance.</param>
        /// <param name="mapper">IMapper instance.</param>
        public LemezController(IBeszerzoLogic beszerzoLogic, ITulajdonosLogic tulajLogic, IMapper mapper)
        {
            this.beszerzoLogic = beszerzoLogic;
            this.tulajLogic = tulajLogic;
            this.mapper = mapper;

            this.vm = new LemezListViewModel();
            this.vm.EditedLemez = new Models.Lemez();

            var lemezek = beszerzoLogic?.LemezRead();
            this.vm.ListOfLemez = mapper?.Map<IEnumerable<LemezBolt.Data.Lemez>, List<Models.Lemez>>(lemezek);
        }

        /// <summary>
        /// Invokes View.
        /// </summary>
        /// <returns>A ViewResult based on the viewname and the viewmodel.</returns>
        public IActionResult Index()
        {
            this.ViewData["editAction"] = "AddNew";
            return this.View("LemezIndex", this.vm);
        }

        /// <summary>
        /// Invokes View.
        /// </summary>
        /// <param name="id">LemezID property.</param>
        /// <returns>A ViewResult based on the viewname and the viewmodel.</returns>
        public IActionResult Details(int id)
        {
            return this.View("LemezDetails", this.GetLemezModel(id));
        }

        /// <summary>
        /// Invokes RedirectToAction.
        /// </summary>
        /// <param name="id">LemezID property.</param>
        /// <returns>A RedirectToAction result.</returns>
        public IActionResult Remove(int id)
        {
            this.tulajLogic.LemezDeleteLogic(id);
            return this.RedirectToAction(nameof(this.Index));
        }

        /// <summary>
        /// Invokes View.
        /// </summary>
        /// <param name="id">LemezID property.</param>
        /// <returns>A ViewResult based on the viewname and the viewmodel.</returns>
        public IActionResult Edit(int id)
        {
            this.ViewData["editAction"] = "Edit";
            this.vm.EditedLemez = this.GetLemezModel(id);
            return this.View("LemezIndex", this.vm);
        }

        /// <summary>
        /// Edits or adds a new lemez entry.
        /// </summary>
        /// <param name="lemez">Lemez instance.</param>
        /// <param name="editAction">Name of the action.</param>
        /// <returns>A redirectaction result or a view result baed on whether modelstate is valid and lemez is not null or not.</returns>
        [HttpPost]
        public IActionResult Edit(Models.Lemez lemez, string editAction)
        {
            if (this.ModelState.IsValid && lemez != null)
            {
                this.TempData["editResult"] = "Edit OK";
                if (editAction == "AddNew")
                {
                    this.beszerzoLogic.LemezCreateLogic(this.mapper.Map<Models.Lemez, LemezBolt.Data.Lemez>(lemez));
                }
                else
                {
                    this.beszerzoLogic.EloadoUpdateLogic(lemez.Eloado, lemez.LemezID);
                    this.beszerzoLogic.KiadasEveUpdateLogic(lemez.KiadasEve, lemez.LemezID);
                    this.beszerzoLogic.LemezCimUpdateLogic(lemez.LemezCim, lemez.LemezID);
                    this.beszerzoLogic.StilusUpdateLogic(lemez.Stilus, lemez.LemezID);
                    this.beszerzoLogic.TipusUpdateLogic(lemez.Tipus, lemez.LemezID);
                }

                return this.RedirectToAction(nameof(this.Index));
            }
            else
            {
                this.ViewData["editAction"] = "Edit";
                this.vm.EditedLemez = lemez;
                return this.View("LemezIndex", this.vm);
            }
        }

        private Models.Lemez GetLemezModel(int id)
        {
            LemezBolt.Data.Lemez oneLemez = this.beszerzoLogic.LemezGetOne(id);
            return this.mapper.Map<LemezBolt.Data.Lemez, WebApp.Models.Lemez>(oneLemez);
        }
    }
}

OENIK_PROG3_2020_2_YR1IG6/WebApp/Views/Lemez/LemezDetails.cshtml
@model WebApp.Models.Lemez

@{ 
    ViewData["Title"] = "LemezDetails";
}

<h2>Egy lemez adatlapja</h2>

@Html.ActionLink("Vissza a listahoz", "Index")

<table border="1">
    <tr>
        <td>@Html.DisplayNameFor(m => m.LemezID)</td>
        <td>@Html.DisplayFor(m => m.LemezID)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Eloado)</td>
        <td>@Html.DisplayFor(m => m.Eloado)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.LemezCim)</td>
        <td>@Html.DisplayFor(m => m.LemezCim)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Stilus)</td>
        <td>@Html.DisplayFor(m => m.Stilus)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Tipus)</td>
        <td>@Html.DisplayFor(m => m.Tipus)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.KiadasEve)</td>
        <td>@Html.DisplayFor(m => m.KiadasEve)</td>
    </tr>
</table>

OENIK_PROG3_2020_2_YR1IG6/WebApp/Views/Lemez/LemezEdit.cshtml
@model WebApp.Models.Lemez

<h2>LemezEdit</h2>

@using (Html.BeginForm("Edit", "Lemez"))
{
    @Html.ValidationSummary()

    @Html.AntiForgeryToken()

    @Html.HiddenFor(m => m.LemezID)

    @Html.Hidden("editAction", ViewData["editAction"].ToString())

    <div class="editor-label">@Html.LabelFor(m => m.Eloado)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Eloado)</div>

    <div class="editor-label">@Html.LabelFor(m => m.LemezCim)</div>
    <div class="editor-field">@Html.EditorFor(m => m.LemezCim)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Stilus)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Stilus)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Tipus)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Tipus)</div>

    <div class="editor-label">@Html.LabelFor(m => m.KiadasEve)</div>
    <div class="editor-field">@Html.EditorFor(m => m.KiadasEve)</div>

    <input type="submit" value="Elkuld" />
}

OENIK_PROG3_2020_2_YR1IG6/WebApp/Views/Lemez/LemezIndex.cshtml
@model WebApp.Models.LemezListViewModel

@{
    ViewData["Title"] = "LemezIndex";
}

<h2>Lemez index</h2>

<p style="color:red">@TempData["editResult"]</p>

@await Html.PartialAsync("LemezEdit", Model.EditedLemez)
@await Html.PartialAsync("LemezList", Model.ListOfLemez)

OENIK_PROG3_2020_2_YR1IG6/WebApp/Views/Lemez/LemezList.cshtml
@model IEnumerable<WebApp.Models.Lemez>

<h2>Lemez lista</h2>

@if (Model.Count() == 0)
{
    <p>Nincs adat az adatbazisban!</p>
}
else
{
<table border="1">
    <tr>
        <th>@Html.DisplayNameFor(m => m.First().Eloado)</th>
        <th>@Html.DisplayNameFor(m => m.First().LemezCim)</th>
        <th>Adatlap</th>
        <th>Torles</th>
        <th>Modositas</th>
    </tr>
    @foreach (var lemez in Model)
    {
        <tr>
            <th>@Html.DisplayFor(m => lemez.Eloado)</th>
            <th>@Html.DisplayFor(m => lemez.LemezCim)</th>
            <th>@Html.ActionLink("[SHOW]", "Details", new { id = lemez.LemezID })</th>
            <th>@Html.ActionLink("[DEL]", "Remove", new { id = lemez.LemezID })</th>
            <th>@Html.ActionLink("[EDIT]", "Edit", new { id = lemez.LemezID })</th>
        </tr>
    }
</table>
}